### ISSUE TITLE
kleine irrelevante typfoutje!

### ISSUE THREAD

**Issue by lemuelmgsn** [MisahSaid/reparatie-end-ass#1]
https://github.com/MisahSaid/reparatie-end-ass/blob/f45a5ac6e772057b6e82faacb25e4c8be6d56437/views/goal.ejs#L18

vgm bedoel je "agency" en niet "acency" ;)

**Comment by MisahSaid** [comment]
hahah idd thank you! [Fixed issue](https://github.com/MisahSaid/reparatie-end-ass/commit/8c2272132b5d5128a42c13ca01800f139dacee6a#)
